### ISSUE TITLE
Nuget requires 3.3.2 of Common.Logging which doesn't exist

### ISSUE THREAD

**Issue by Guy--L** [pbolduc/Common.Logging.EventSource#2]
Did you set your requirements version to 3.3.2 for Common.Logging because I cannot find it anywhere?

**Comment by pbolduc** [comment]
You are correct.  I had the wrong version in the nuget package.  I have updated the package to use the latest version of Common.Logging, version 3.3.1.

**Comment by Guy--L** [comment]
Thank you.
